# Site settings
title: A-Star Academic Services
email: youremailaddress@gmail.com
description: A site for losers.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com

# Build settings
markdown: kramdown
