backend:
  name: git-gateway
  branch: master

media_folder: "posts"

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    editor:
      preview: false
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", default: "../banner.jpg"}
      - {label: "Post Description", name: "description", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}