backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/"

# TODO: Make every part of this site editable!!!
collections:
  - name: 'pages'
    label: 'Pages'
    delete: false
    editor:
      preview: false
    files:
      - label: "Social media"
        name: "social"
        file: "data/social.yml"
        fields:
          - { label: 'Title', name: 'title', widget: "string", default: "Pricing" }
          - { label: "Description", name: "description", widget: "string", default: "Academic experts at your service." }










  # - name: "posts"
  #   label: "Post"
  #   folder: "_posts"
  #   editor:
  #     preview: false
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Main Image", name: "image", widget: "image", default: "../banner.jpg" }
  #     - { label: "Post Description", name: "description", widget: "string" }
  #     - { label: "Content", name: "body", widget: "markdown" }
